






import { GraphController } from '../init.js'
import { LZW_decompress } from '../../helpers/lzw_compression.js'


{
    const presets = 
        { 'LFO Example 1': `{"connections":{"0":[],"5":[{"id":0,"connectionType":"channel"}],"6":[{"id":7,"connectionType":"channel"}],"7":[{"id":5,"connectionType":"frequency"}]},"nodes":[{"id":0,"type":"gain","x":0.24,"y":0.5690346083788707,"title":"OUTPUT","audioNode":{},"audioParamValues":{"gain":0.25044590807994566},"audioNodeProperties":{}},{"id":5,"type":"oscillator","x":0.39999999999999997,"y":0.5690346083788707,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":200,"detune":0},"audioNodeProperties":{"kbMode":false,"type":"sine"}},{"id":6,"type":"oscillator","x":0.24,"y":0.3414207650273224,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":4,"detune":0},"audioNodeProperties":{"kbMode":false,"type":"sine"}},{"id":7,"type":"gain","x":0.39999999999999997,"y":0.3414207650273224,"audioNode":{},"audioParamValues":{"gain":100},"audioNodeProperties":{}}]}`
        , 'LFO Example 2': `{"connections":{"1":[{"id":3,"connectionType":"channel"}],"3":[{"id":0,"connectionType":"channel"}],"4":[{"id":3,"connectionType":"gain"}]},"nodes":[{"id":0,"type":"gain","x":0.24,"y":0.853551912568306,"title":"OUTPUT","audioNode":{},"audioParamValues":{"gain":0.11230623494142718},"audioNodeProperties":{}},{"id":1,"type":"oscillator","x":0.39999999999999997,"y":0.853551912568306,"title":"oscillator","audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":220,"detune":1.6484375},"audioNodeProperties":{"kbMode":false,"type":"sine"}},{"id":3,"type":"gain","x":0.39999999999999997,"y":0.6259380692167578,"title":"gain","audioNode":{},"audioParamValues":{"gain":1},"audioNodeProperties":{}},{"id":4,"type":"oscillator","x":0.24,"y":0.6259380692167578,"title":"oscillator","audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":8,"detune":0},"audioNodeProperties":{"kbMode":false,"type":"sine"}}]}`
        , 'LFO Example 3': `{"connections":{"7":[{"id":0,"connectionType":"channel"}],"9":[{"id":7,"connectionType":"gain"},{"id":10,"connectionType":"channel"}],"10":[{"id":11,"connectionType":"frequency"}],"11":[{"id":7,"connectionType":"channel"},{"id":7,"connectionType":"gain"}]},"nodes":[{"id":0,"type":"gain","x":0.32,"y":0.5121311475409835,"title":"OUTPUT","audioNode":{},"audioParamValues":{"gain":0.15},"audioNodeProperties":{}},{"id":7,"type":"gain","x":0.44,"y":0.3414207650273224,"audioNode":{},"audioParamValues":{"gain":1},"audioNodeProperties":{}},{"id":9,"type":"oscillator","x":0.19999999999999998,"y":0.3414207650273224,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":4,"detune":0},"audioNodeProperties":{"kbMode":false,"type":"sine"}},{"id":10,"type":"gain","x":0.19999999999999998,"y":0.6828415300546448,"audioNode":{},"audioParamValues":{"gain":100},"audioNodeProperties":{}},{"id":11,"type":"oscillator","x":0.44,"y":0.6828415300546448,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"triangle","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":200,"detune":0},"audioNodeProperties":{"kbMode":false,"type":"triangle"}}]}`
        , 'LFO Example 4': `{"connections":{"1":[{"id":3,"connectionType":"channel"}],"2":[{"id":3,"connectionType":"channel"}],"3":[{"id":6,"connectionType":"channel"}],"4":[{"id":1,"connectionType":"frequency"},{"id":3,"connectionType":"frequency"}],"5":[{"id":4,"connectionType":"channel"},{"id":7,"connectionType":"channel"}],"6":[{"id":0,"connectionType":"channel"}],"7":[{"id":6,"connectionType":"pan"}]},"nodes":[{"id":0,"type":"gain","x":0.19999999999999998,"y":0.910455373406193,"title":"OUTPUT","audioNode":{},"audioParamValues":{"gain":0.11197857737804542},"audioNodeProperties":{}},{"id":1,"type":"oscillator","x":0.36,"y":0.22761384335154825,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":400,"detune":1.6484375},"audioNodeProperties":{"kbMode":false,"type":"sine"}},{"id":2,"type":"buffer","x":0.52,"y":0.4552276867030965,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"loop":true,"bufferKey":0,"detune":{},"playbackRate":{},"soloSource":{}},"audioParamValues":{"playbackRate":0.2726543170166016,"detune":0},"audioNodeProperties":{"kbMode":false,"bufferKey":0}},{"id":3,"type":"filter","x":0.36,"y":0.4552276867030965,"audioNode":{},"audioParamValues":{"frequency":605.041686296463,"Q":1,"gain":0.5,"detune":0},"audioNodeProperties":{"type":"lowpass"}},{"id":4,"type":"gain","x":0.19999999999999998,"y":0.22761384335154825,"audioNode":{},"audioParamValues":{"gain":300},"audioNodeProperties":{}},{"id":5,"type":"oscillator","x":0.19999999999999998,"y":0.4552276867030965,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":8,"detune":0},"audioNodeProperties":{"kbMode":false,"type":"sine"}},{"id":6,"type":"panner","x":0.36,"y":0.6828415300546448,"audioNode":{},"audioParamValues":{"pan":0},"audioNodeProperties":{}},{"id":7,"type":"gain","x":0.19999999999999998,"y":0.6828415300546448,"audioNode":{},"audioParamValues":{"gain":-0.5},"audioNodeProperties":{}}]}`
        , 'LFO Example 5': `{"connections":{"4":[{"id":6,"connectionType":"pan"},{"id":9,"connectionType":"channel"},{"id":7,"connectionType":"channel"}],"5":[{"id":6,"connectionType":"channel"}],"6":[{"id":0,"connectionType":"channel"}],"7":[{"id":6,"connectionType":"pan"}],"8":[{"id":5,"connectionType":"channel"}],"9":[{"id":5,"connectionType":"frequency"},{"id":8,"connectionType":"detune"}]},"nodes":[{"id":0,"type":"gain","x":0.44,"y":0.22761384335154825,"title":"OUTPUT","audioNode":{},"audioParamValues":{"gain":0.10032848662775919},"audioNodeProperties":{}},{"id":4,"type":"oscillator","x":0.32,"y":0.5121311475409835,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":8,"detune":0},"audioNodeProperties":{"kbMode":false,"type":"sine"}},{"id":5,"type":"filter","x":0.5599999999999999,"y":0.2845173041894353,"audioNode":{},"audioParamValues":{"frequency":1000,"Q":1,"gain":0.5,"detune":0},"audioNodeProperties":{"type":"lowpass"}},{"id":6,"type":"panner","x":0.44,"y":0.39832422586520944,"audioNode":{},"audioParamValues":{"pan":-0.5},"audioNodeProperties":{}},{"id":7,"type":"delay","x":0.32,"y":0.2845173041894353,"audioNode":{},"audioParamValues":{"delayTime":0.75},"audioNodeProperties":{}},{"id":8,"type":"buffer","x":0.5599999999999999,"y":0.5121311475409835,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"loop":true,"bufferKey":0,"detune":{},"playbackRate":{},"soloSource":{}},"audioParamValues":{"playbackRate":0.4,"detune":0},"audioNodeProperties":{"kbMode":false,"bufferKey":0}},{"id":9,"type":"gain","x":0.44,"y":0.5690346083788707,"audioNode":{},"audioParamValues":{"gain":800},"audioNodeProperties":{}}]}`
        , 'Binaural Beat 1': `{"connections":{"1":[{"id":5,"connectionType":"channel"}],"3":[{"id":4,"connectionType":"channel"}],"4":[{"id":0,"connectionType":"channel"}],"5":[{"id":0,"connectionType":"channel"}]},"nodes":[{"id":0,"type":"gain","x":0.5599999999999999,"y":0.3597696737044146,"title":"OUTPUT","audioNode":{},"audioParamValues":{"gain":0.11079825893328435},"audioNodeProperties":{}},{"id":1,"type":"oscillator","x":0.64,"y":0.65957773512476,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":204,"detune":1.6484375},"audioNodeProperties":{"kbMode":false,"type":"sine"}},{"id":3,"type":"oscillator","x":0.48,"y":0.65957773512476,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":200,"detune":0},"audioNodeProperties":{"kbMode":false,"type":"sine"}},{"id":4,"type":"panner","x":0.48,"y":0.47969289827255274,"audioNode":{},"audioParamValues":{"pan":-1},"audioNodeProperties":{}},{"id":5,"type":"panner","x":0.64,"y":0.47969289827255274,"audioNode":{},"audioParamValues":{"pan":1},"audioNodeProperties":{}}]}`
        , 'Binaural Beat 2': `{"connections":{"1":[{"id":5,"connectionType":"channel"}],"3":[{"id":4,"connectionType":"channel"}],"4":[{"id":0,"connectionType":"channel"}],"5":[{"id":0,"connectionType":"channel"}],"7":[{"id":4,"connectionType":"pan"},{"id":8,"connectionType":"channel"}],"8":[{"id":5,"connectionType":"pan"}]},"nodes":[{"id":0,"type":"gain","x":0.5599999999999999,"y":0.41973128598848364,"title":"OUTPUT","audioNode":{},"audioParamValues":{"gain":0.11230623494142718},"audioNodeProperties":{}},{"id":1,"type":"oscillator","x":0.64,"y":0.65957773512476,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":204,"detune":1.6484375},"audioNodeProperties":{"kbMode":false,"type":"sine"}},{"id":3,"type":"oscillator","x":0.48,"y":0.65957773512476,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":200,"detune":0},"audioNodeProperties":{"kbMode":false,"type":"sine"}},{"id":4,"type":"panner","x":0.48,"y":0.47969289827255274,"audioNode":{},"audioParamValues":{"pan":-1},"audioNodeProperties":{}},{"id":5,"type":"panner","x":0.64,"y":0.47969289827255274,"audioNode":{},"audioParamValues":{"pan":1},"audioNodeProperties":{}},{"id":7,"type":"oscillator","x":0.5599999999999999,"y":0.7195393474088292,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":2,"detune":0},"audioNodeProperties":{"kbMode":false,"type":"sine"}},{"id":8,"type":"gain","x":0.5599999999999999,"y":0.5396545105566218,"audioNode":{},"audioParamValues":{"gain":-1},"audioNodeProperties":{}}]}`
        , 'Rhythm 1': `{"connections":{"24":[{"id":0,"connectionType":"channel"}],"25":[{"id":29,"connectionType":"channel"}],"26":[{"id":28,"connectionType":"channel"}],"27":[{"id":24,"connectionType":"channel"}],"28":[{"id":24,"connectionType":"frequency"}],"29":[{"id":28,"connectionType":"channel"}]},"nodes":[{"id":0,"type":"gain","x":0.16,"y":0.7397449908925319,"title":"OUTPUT","audioNode":{},"audioParamValues":{"gain":0.1265614239293618},"audioNodeProperties":{}},{"id":20,"type":"gain","x":-0.6384615384615384,"y":-0.10805500982318271,"audioNode":{},"audioParamValues":{"gain":0.5},"audioNodeProperties":{}},{"id":24,"type":"filter","x":0.32,"y":0.7397449908925319,"audioNode":{},"audioParamValues":{"frequency":100,"Q":1,"gain":0.5,"detune":0},"audioNodeProperties":{"type":"lowpass"}},{"id":25,"type":"oscillator","x":0.16,"y":0.2845173041894353,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":3,"detune":0},"audioNodeProperties":{"kbMode":false,"type":"sine"}},{"id":26,"type":"oscillator","x":0.48,"y":0.5121311475409835,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":2,"detune":0},"audioNodeProperties":{"kbMode":false,"type":"sine"}},{"id":27,"type":"oscillator","x":0.48,"y":0.7397449908925319,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":200,"detune":0},"audioNodeProperties":{"kbMode":false,"type":"sine"}},{"id":28,"type":"gain","x":0.32,"y":0.5121311475409835,"audioNode":{},"audioParamValues":{"gain":100},"audioNodeProperties":{}},{"id":29,"type":"gain","x":0.16,"y":0.5121311475409835,"audioNode":{},"audioParamValues":{"gain":1},"audioNodeProperties":{}}]}`
        , 'Rhythm 2': `{"connections":{"24":[{"id":0,"connectionType":"channel"}],"25":[{"id":29,"connectionType":"gain"}],"26":[{"id":29,"connectionType":"channel"}],"27":[{"id":24,"connectionType":"channel"}],"28":[{"id":24,"connectionType":"frequency"}],"29":[{"id":28,"connectionType":"channel"}]},"nodes":[{"id":0,"type":"gain","x":0.16,"y":0.7397449908925319,"title":"OUTPUT","audioNode":{},"audioParamValues":{"gain":0.11228846267698643},"audioNodeProperties":{}},{"id":20,"type":"gain","x":-0.6384615384615384,"y":-0.10805500982318271,"audioNode":{},"audioParamValues":{"gain":0.5},"audioNodeProperties":{}},{"id":24,"type":"filter","x":0.32,"y":0.7397449908925319,"audioNode":{},"audioParamValues":{"frequency":100,"Q":1,"gain":0.5,"detune":0},"audioNodeProperties":{"type":"lowpass"}},{"id":25,"type":"oscillator","x":0.16,"y":0.5121311475409835,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":3,"detune":0},"audioNodeProperties":{"kbMode":false,"type":"sine"}},{"id":26,"type":"oscillator","x":0.48,"y":0.5121311475409835,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":2,"detune":0},"audioNodeProperties":{"kbMode":false,"type":"sine"}},{"id":27,"type":"oscillator","x":0.48,"y":0.7397449908925319,"audioNode":{"ctx":{"analyser":{},"volume":{}},"volumeNode":{},"playingKeys":{},"stopLastNSources":[],"_kbMode":false,"_type":"sine","detune":{},"frequency":{},"soloSource":{}},"audioParamValues":{"frequency":200,"detune":0},"audioNodeProperties":{"kbMode":false,"type":"sine"}},{"id":28,"type":"gain","x":0.32,"y":0.5121311475409835,"audioNode":{},"audioParamValues":{"gain":100},"audioNodeProperties":{}},{"id":29,"type":"gain","x":0.32,"y":0.2845173041894353,"audioNode":{},"audioParamValues":{"gain":1},"audioNodeProperties":{}}]}`
        , 'Weird Rhythm': `{"connectiăs":Ā1Č[ĀidČ8,āăąćĉnTypeČāhaĄel"},ĒĔ:13ėĂĦěăĞĠĢpĥĩ]ė6ĐĬČ1ıęĆĈĵğġ:"frequencyĻė7Ŀ"ēČ6ŃĳņĝňĢcĤĦĨĪŀĮŜĘŞĜĶŉ"gainŕ"8ŘŚĮİūĚşŮŢŤąŦļ"įŸĭ0ŝŽŭšŊţĥƂŵ15ƇŁŪĲƋŇķƎƁħƒľ:đřĭ17ƊŅƌƛģƐƞ}Ƅƥƕ:ƉżƨƚůƏťƒ9Ʊ2łƴĴŠƪƸƑƮėƽƱƦƿžƍŋōŏőœŵ22ƼŻƘƵǁƷƝƃǆ3ƼƾǗǀſŊűųĻĪ"nodeċơŨƳtǌǥŴėĈtlůǴ"ėxČ0.32394630344ƽ014ėŔƲ.125675ș49į279ǉaudĉNǫŉ{ǨȣȥoParamValŐǮĀǻȓƓ3Ȃȉȕ5}ŧƣŁǶǌoscillatorǼ"ǷǹĢɈɊɌɎɐɒǾȓ5ȃȅȇȉȋȍȕȑǿ.Ȍ548381ȇȽ6ȖȏėȬȦȨČĀMONOś66ȌƳćɝȪėkbMɹŊǪąɒǡteǭĿŧǅ"sourcʔč"ʁʂ20ɺɂėADSRȸʠʁʃɺ"ōǹaseIĭ-1ʦ"_ǲƪsawɏothɒǬtuʏʟsʜʥǨŌŎŐŒȒĀˍcˏȫȤɸǬǣʘˁ˃˅ɒɷȮȰȲȴȶʞĀˑǏ˔śȐ"ˈˊŉ1.ʂ843șʦŨŪʾǺŲǵɓiǸ̀ǦǽɨɟȄȆȈȊȌ1Ȏ2ɧȓʁ5Ƚ026ɫ699ȎŪˤȧǬʥɶ˛˥ȱȳȵȷʰȺʣ0˼Ʉ:ǉ˿ɖɉɋɍɏɑǶ̄ɕŊɗ̷ɚ̺"ɝȀ3ȇɡ̍ɤ̐ȏ˰ȒȀ̛̗̙̝̟̥̕ȭ̢ȩ"ɼɾʀʢʄtʆǨʉʋ̣ʍăġƧćʓǮđʖƄʙʛʝʬʡʯčʻʨʪͳʮʣʰʲeʴʶʸʺǨʽǌsųͨ˱eˉˋ˖ˎͶːǎ˓ǑˌΏȪʻ̡Ȩ˞·ʏ͖ĉǫ̇˨̫ʟˬΓ͎.șė˲ˋ̯ɃŹĖɓǌfɋʒ͂ɔůγlεɜɨ͆̋ɢ̎ɥȋ̓ȀɪɬɮɰȽ͆ɴ˰Ιͥʇ"ώe˞lowĹsċΞ̧˧̪˪Ǎ˒ǐȒȕȀ5į80̝Ț7˸0ΰQɅŰ́̉Ϊ΋˳ǿ̰Ź1ƾ̴ŊĹĦζ̼ůϿą͂̈́ɩ˹̘ƥʁ9̚Ȍ8ȅ̓-Ȁ05ȗɳ18Ϩ̝ϨϨ̠̦̤͘ϑ̦Πϝ˩ʬϿϸήƤŻϽ"ЄeЁ̅ĸƬІɨȋο͉̏ȎŻΧ24Ж9АȠɬȏƥ9ϛСͶϛХ̩ЧʰЩƲϹƤ5Ɇƪ̿ə̹ɒη̵ɘ̸ɛ̈ȓпйɣлɦ"Χɫɫ0704ϩȎ7ȇύРʌɻɽɿ:ʹʣı͠ТͣʌǩͧʐńͪʞͭͯʚʜϟѻʤΐʧʩʫʰҍͽħͿʵʷČʹʻ΅ʿΈˇ϶΍ʘΖʻΥϢʰ˗˙щΚΆҟь˦юΣ˫ΒҧĮįϵΌŉέī̱ɰі̆̂ќǤϳѡȀω͈ѥςнɨ͐Ȉ͒Ȇ͔ҾУ͗Ѷ˚ȭэ΢ϟȺ΃ҼϺ̳ǳӄ̃гӃ̇̓ɨӇ̌Ӊ͋˹τ.псуȅɯ4чҫϏӖΟҰәʬȺϥѓŁшαї̶љѠӢ̽"јџжȻɠөρӫǉΧϬɟ̖Ȝ0ȉϨȄȢѵϏ͚Ѹ͝ʃѽ͡ʈʊҁʎΉʑͫʕ҉ͱҌͻҎΗҐ͹ғ԰ҕʳҘ΂ҜЮsŏȰΉΫ͙ҩҏϠ˭ΔΎ˘ΐӸo͘ΛԾōˣФӺϞʬҦˮĮ̘˰ՁЪӝĭѼԂӀћЂĢǻѡГ˶ɮȆȼ˸6ի͍ҚӆϮЕ5ԘтȃЙȟƾϒТˤӘՔ̬ϳɞӿ:ƽҿդӡӂϲӥЇ2ɭӈԐ̑Ūԓ8ԕȊ̞ԙȉȡӶȩՋվяʟ̭ԘփǓֆ̾Ԅԋբӣԉ֧́μ̔֙ԏ͊мӭԔȖ֖Ԙɮ֙ԜӔԞ͛ѹҍԣѿԦͥ҂ΝǊԫǯʗͰҋͺ͞ˏԳҒʟҔʟ;΀ҙ:қ΄ԼҮΊҹҨҤΑϡ՗ՈҪӓ˜ϓҭ׆սՓ֟ҳעΔΰ՛ђЫČȃ֥֊ӁգӤ̂Їи֏ֲҷѨɨֵԖֹ֗ԛ֛ռՒΡտ֠ցѯέ]}`
        , 'Keyboard 1': `{"connectiăs":Ā1Č[ĀidČ0,āăąćĉnTypeČāhaĄel"}]ė2ĐĒĔ:ĖĘĦěăĞĠĢcĤĦĨĪ}ėnodeċ:đ"ēĕėtğġ:"gain"ėxĕ.240ŜŝŞŞ2ėyŘ3ś9606986899563ėaudĉNłŎ{Ŀ"ŵŷoParamValuńČĀőœŘ48ũ6ś625ş04ŽſŸźProĠrĈƋč}ĿįČ1ŋōĢoscillatorŕ"ŗı.3š"ţƽ511441ƚƒť9ť5ŴŶƞŃƌātƼĀvoƉmŻƨėADSRŅżėǙǛeŹǓƧėpƵyœgKeyǤŽsƷpLaǸNSourcƦđƩȆ,ǥȉȆī"_kbMźČtrƊė_ŌĸŏsœġėŃtuąƌŽfreqƊncǂżƜǑƁƃƅƇƉƦĀȦȨȪȬƫǉȟeȡȣ:1.Ɣ84375ȯƀǪeƠƢeƤiȶ"ȏȑǫȔȖ"șŎ"ȜȣǞƪ:ǀɜĢbuffɑƺƼ0.16ŢŘǄǆǈǊ0ǌǎǐɌȒčǕǗ"ǧuǜȤŽǠǢǶǦǚʃǩɽǥ"ǮaǰnǲǴʉɞǹǻǽǿȁȃŅȅȈȇȊʡʡȌȎȐɽəeėloƢȓȕʫ"ɧɩɑǳǂĲȠȢǝǭǯbackRƶǝɋĉƂƄƆƈƊǤʐʾˀ˂˄Ř23ű˕ȾɀŎ0ˆoɍɏƣƥˍɖʩʱėʴɪrʷĕƨ]}`
        , 'Keyboard 2': `{"connectiăs":Ā1Č[ĀidČ3,āăąćĉnTypeČāhaĄel"}]ė2ĐĒĔ:ĖĘĦěăĞĠĢcĤĦĨĪė3Į"ēČ5ėĂĴĈĶğġ:ģĥąĽī"4ŁŃ:6ņęĆŉĝŋĹĻŐĩŒ5ŕİ0řňĜķŌŎļŢė6ťńŨĚŜūĢfrequencyŢ}ėnodeċ:đłŦėtŞōgain"ėxČ0.559ƞƟƠƠėƁ:ƚ779500Ʃ96928982ėaudĉNƆŌ{ƃ"ƷƹoParamValŽƉĀƒƔƙ.480664Ǖ2ƪƫǜ4ƿǁƺƼProĠrĈƈČƾƃįČ1ƎƐ"oscillatorƖ"Ƙƥ.6ƨơȄƞƣǑƝƮ1612ƱǘƯǯǀƸǡƇǪātǿĀvoǋmƽ}ƿADSRǍƿȜȞeƻȖčƿsourcǩȮėpǸyƔgKeyȧėsǺpLaɂNSȱȳȵđǬɎ,ƾɐɏɑɔɎŒ_kbMƼČtrŽė_ƏĸōsƔġėƇtuąǪƿŹŻŽſƤǫƶȔǃǅǇǉǋȵĀɰżžƀǮ1ŧ"ɪɬŌ1ȁǓ4375ǟɷȬeǣǥeǧiɽ"əɛȭɞɠ"ɣŬɦɭȡɐƌČƵʡǱbuffʗǽǿƚ44ȇȀȉȌȌȎ8Ȑ9ȒǠoʓȗćȚ"ȩuȟɮȢȤȦɮėˈȟ˃ȶ"ȰȲȴɀ"ȸaȺnȼȾ˙ɂǥɅɇɉ˗Ɍɕɒ˪˩ˬɖɡʜɜ:ʟeėloǥɝɟ˴"ʭʯʗȽƤʅʇɭ˔˛ybackRǹȠʑǂǄǆǈǊǌȗ̆̈̊̌tŌƚ2356̟ɩeɫ̄0̏ȕʔǤǦǨǍʛɚ˱˳ė˽ʰr̀ƙʦǭıǰɤ"ǏƕƗȈȉȅơʷʴ1973ȍ8Ɲ8ʽ83Ǘɶǂ˓ɑȓ̐ɹ̓ɼ̮̿Į̏˂Ǣ̫ʗ̭ˋʧŖʶʫ̽ǳǵǷǹǻʲǑȂ̈́Ȅ͆.ƧƩƫƭƯƱƳʪˁ͖Șˆˑ̎ėȣȥ˙΄͖ȯɊ˘ˏ˚ȹȻ̀ˡɃˤtɈ΍Ɍɗ˰ȭfǊs˻ɢǱʤɨʆ̤ʈΏɿɲʂ˔Ȱ˶˦ɋͦ͘ĉ̑ɺ̔ʚΪʁ́.ʽ9̟ξ34ȉȏ9̣̥̜͠ʓʕ̬ʙ̮ΜŌΞlΠ̼ʣɧĩǬʨ:ŅͪŬfǶ̛Ǽ́ȀʵͶ͸ǛͻưƲƴ͔̩Ώˁε͛̕č"ιɳČʵʅQǮė͞ʸφΨƥω͢ʖʘʚʢĢ˶wpɆċ̹ϙŘϜĢ͞ϢƚƜʹͅ"λʹȋȍȏǕʿϬ͡ȭ͗ϯ͚ɻϲǎƓƕıƫЂƇϋͤύˋ]}`
        , 'Crazy Keyboard 1': `{"connectiăs":Ā1Č[ĀidČ4,āăąćĉnTypeČāhaĄel"}]ė3ĐĒĔ:ĖĘĦěăĞĠĢgainĩī"4Į"ēČ0ėĂĴĈĶğġ:ģĥąĨĪė5łń:3ŇęĆŊĝŌĢfrequencyľė6Ŗİ5ŚŉĜķōŏĦŒ]}ėnodeċ:đŃİņ"tşŎĺļ"ėxŅ.4Ĳũ:0.284517304189435ř"audĉNżō{ŹƦƨĉParamValťſĀƉĽ:1.1998Ɲ68750ǌǌ1ƯƧƩoƫŽProĠrĈžČƮŹįČ1ėƆĸŎoscillatorƋ"ƍƓƏƑƎƙ213114Ǌ40ǅƣėǑƪƬǝātǳƮėADSRƼŀ8ȈŢleaseIİ-Ǐė49ȕħȘȚȜČȞƯǋȣȗșțȝȟ"ƙȬȥȯȨȱ52ȴȮȧ:ȩŔĭč"ȖȵȽȿȲŁɂɄȼȰȪŕɊȤɌȷȪŬɐȭȦɍŔ7ȻɘɓūɏĀɋɝȾȱ6ɕɡɑɣɇ6ɛɖɅə"ǈɜȶɤƯ6Ȣɮɒɵė70ɳȽɬǌƯ7ďɹɣ6ƙȱ7Ⱥʆɴɬ24ʃɁɨɗɴɇ7ɉʔɯČʈƢʃɠɃɩʎʘ5ʃɧʡʕɆʊɭʚɺʗȔʍʪʃɸʭɪȱǆɿɰ8ʅʵʖʷʌʽʲė8ʓʨʛɻ"ƗʹɞˉʠɢʾƯ8ʧˏ˂ˉʬˆʮʷʰˁʺʴ˘ʶƯ9ɾʱɰƟ˓ʢ˕Ɵ˗˔˥8˛˟ːėƟ˞ˬˌǃˣ˜˶9ʼ˰˕ǹ˴˨ɰ2ǹˋˈ̃ˀ˽ɍƯvoƺmeǔƭƯMONOʜɦ42Ƅ_kbMȇŎp̍ũėsourcǜɂ4˛ƯȡǝȪ˸ȪʼȪˀȪʓȪʙɎ̲ŔɧȪʬɶɠɶ̀ū͂ū̯ūʴʃ˸"ĤsStƴteİtrťʃ˼͔͖͐͒Č͚͘ɼ͓̈͝ǚ͠:͢eʒ̾"ʘȈ͙ͦ͗ͬ͟ɼʠͲͨʹ͈ͣͯ͆ͯͯ͊ͯ͌˃̴˃̶˃̸˃̺˃̼˃̈́˃;ǉͮˮΔ΄"ˢͮ˦ΚΓčƯƟ΂˳ΚΙΞ˲˻ͮ˿Ψ̄Υ"̲̇Ų̛tputſ[Ŀ_ǤŴsļġėŽtuąȈs̪ίėšţťŧƒĀυcίǐƱoƳƵƷƹƻȈωŤŦŨǡ1Ƅπςōǁ6̮ƢǊϒǒ̑ǖǘeǚi̬Ā̞̠ŽĢ̣l̥ƅƇ"μσ}ǟƂČƥκĢǧǩǫǭǯǱǳƔ27ǄБВГ7ėƒƔǸǺǼǾ5ȀȂůưϫ̡ĀćȋƯȎȐȒ̮̅ɇ̱ˤˌȫЯˈȳвɇȹЬȸ˅˵гʙ̉аˎ́а˧ʩɰ5˫сˈʈиͅы͇эɱ˯лɫ̀фˌɽ̅ʁʊ˼лʈ12ʃ̈ќʋʥɼкшʗнќНʑͷјʘ6ʦя7чѕˈ7ёѧʊєˇɇʸеʷћѹˑѡ҂΋яˊѿˑрѵѽуѼʷѴҏˑѸҌʷѻ˙ˡ͎ђȱΛ҉˲Ν˹ˈΠя΢Ҟ"˷ҤΧҦΩҫΫҡɇή҉̋̍ȕ̖̘̑ͮ̔Ϧ̛ė̡̝̟"ϸϺ̧̩̫Ъ΂ЮȌȲΆȲΈȲΊȲΌɈͮ5ΐȲ;цͮъάɦӛ΀ɲӝΗїɂ͹͕ͻͶͯ͜ș͞ͺ͡͵ѠͱӬͧӧӯͼƛͮͰӥӳͳӶөǊӲ͑Ӵͩͫѱάѳӹ΂АΔӍʻΔӑ˄ΔΎˍΔΒ΀ΕάƠͮΤӋҝԝҠΟԘԟΗҨάǃӏҬӋ̃Ԩ̃χ"αγεĐθЅŎϾξ"ϢσɂϏԮϛϋϞԼφΞЀȄϓϕƶƸƺϲ"ԿϝƒǊƕ0ʄ06ǼǹƤǅοeρԻ0ϪȆǕǗǙǛȒϴӁӃǱԵϽνĩЁŗĲիƾЌƎЏГշБЕ"ЗƕƗƙƛƝ˳ƢƤՆТ϶άȅϔƴՉϘՌճǴѤСաeϭդϱƼՅǠ:РղĻĽƌƎўЖǷўКǽǿȁ˄Р։ҷֈՇ֋ϗՋȒ֏ǆՠǓƬ֕ϯեχ֚6ǣϼЇǪǬǮǰ֠Ǵ֢ջյվƚƜƞƠփƥ֬УȉЦȍȏȑȈЫҦӊогҚ҅ӎязҦƤעѩנӖעҎҘɚяӜүɥ׫ˠюҦӡװɶҗ׳ͯןѵʁџɼҁ׽ƙ3ӱвʏѰѥѲק؂ƘʟѮǾԆ׷ɼґ׬΁Ѳ׹˱ˉ׼Ғ·҇҄ҕˑѦؠ΍҇ҋ؜ˉײؙҠםѽҔاԚҦԜجҜ˒ҤثқԡخؕҥؒҧزظΦ؁اԩسƯԫяұ׷ҳ̎̐У̗̓̕:ɦҼ̜էևӂ̤ǱӅ̪ՌךӋӊ̳ӕӏףӋץάНӕӗ5әӠӗӞӝӠ΂ɷӹ͎ӦԄӰ؀ԁӭӵͪٸͯͥӼӮٽӷӓӺĀٶӨ؎ӻԂӽڃӿ;ԈԇԊΗѾӋԎԙԐӓ҈ږӗصԙԗ΂ذӋԜԡ;˪ΜΡڢΟڤفΨǃΪԬ̸ΰδԱζԴϼԷǱԺƭϽՃǞψŢϜότھЀֶՈֱϙɂՎۃْ.˻ў5ˢƐ2ے0̃РڻŅֶϬգֺ֗ȈٖŴթֿǥլϿĪ}`
        , 'Crazy Keyboard 2': `{"connectiăs":Ā1Č[ĀidČ4,āăąćĉnTypeČāhaĄel"}]ė3ĐĒĔ:ĖĘĦěăĞĠĢgainĩ,įČ0ėĂĴĈĶğġ:ģĥąĨ}Ŀ"ēČ7ŃęĆņĝňĢcĤĦŎī"4ĮőİłĳĚŘķŉŋŞĩŠ5ţŒ:1ŕŅĜŪĢdetuąľŀ:3ŵŨŷŚŊfrequencyŮė6űİ5ƃŗƅĸŊŜŌħƑ"7ƔČŴŧƘŇƚ"ƈƊƌƎƐŏƀƤńƄƧūźżžĪŏ"noźċ:đŤŁėtƆ"ĺļ"ėxŁ.4ĲƐ:0.341420765027322ĲaudĉNƽŉ{ƺǥǧoParamValƌƿĀǈĽǒ.ǟ36ǡ812ǝ0ȈȈ4ǭǦǨǪProĠrĈeǺ}ƯǂųǄǆoscillatorǊ"ǌǾǟ9ȭȮȯȯŔ"ǑǓ796648451Ǡ0ǖ89ėǮȎźČĀćȪĀvoǸmǫȘėADSRǺš8Ɉ"ƉleaseIİ-1ƺ49ɛɝɟɡɣČɥƺǝɪħɬɢɤɦėȽɳɞɠɶɯɸ"52ɻɵɮ:ɰɹĭčɜɴɽʆʈʁŢʋɫʎɷɱŰʓʍɭʖɹƓʙɼʛɿɱơʟʅʜ"ǜʄʕʢƒʞĀʔʡʇʀ6ʤʯʚɾʲƺ6ɚʥʫʹƒɩʽʱ5916ƺ70ʪʱʐ7ď˂ʸˍʃːʏʀǠˋˑ˖ʒʶʠ˙ˈʘ˜ʦʬƠʮʌ˝˕ˈʵ˦ˢʿƠʼˡʾˍˁ˰ˌʀ8ˊ˔ʧȄ˘ʆ˄19ƺ8˓˴˞ė8ʊ̄˨̆˛˫ʾ˾3́ˠ̍˵́˥ʰ̅"8˪̗̙̊˯̘̓ɂ˼ʧ9˸̉ʧ18̖ʷ̨̛̝̩̬8̟̜̱˳̠̭̥̣ˣ˿ˏ̧ˣ2˿̺˭Ǣ̷̽ʧǢ̃͆ʢƺɍɏeǩɇčƺMONOČȸȹǙė_kbMǪĢpɎƐėsourcȖɛȺɈɧ˳ɱ̦ɱ̽ɱ̃ɱ̈ɱ˛ʗͯʝͽʁʵʺˠʺʮʺ΁ƒ˯ʺ̶ĤsStǲteİtrƌˈͳėˎͿ7ͷΙ͹ΙͻΙ΃Ι΅Ι·ˮΛͱ̆Θ̙ͅΌΎΐΒČΔΖ̆Ν̙Ο̙̌ίΏȔβ:δȇͿ̪τΧ̲τΪ"̹͒ė̩Υ"̮Ϳ̩Ήώ̢ύϑόǬώ˅Ϳ̀ϊ̈́ϞǢͯƺͨtputƿ[Š_ǅƨsawȥothȨƶŽɑėƪƋƍƏϤɄȍǰǲǴǶǸͬʋϽƬЀ:ȹėϹžų.ȹȻ375Ȍǯ͐eȐȒeȔiЉĀ͑͞͠"ͣlͥ"ϯūϱϳoϵϷɒƀƂЬȝȟȡȣȥȧǋǍȬȰсȭȲȴǔǖǘǚǜǞǠǢǤЃМɛɊɛ͍uɐЁ"ɔɖɘͮ˹ˣɨ͂ʐɲѝ˭ɺѣѡ̴͉ˣ5̈͊Ѥ̌ѩѤ̒Ѱѡ̫˧ʧ5̯ѶˣʩѦʳѵˬʐʴѠʳ̳̰ѻ̶Ѱ˾7Η҃ˈͅѳ˖Ѩ҆˭˗ѽˈѯғˍѲҙ˖ѿ˱˖ѹҀ˖҅ѺҔ҈Ҝ̦́ѭʐ˻ѣ˄Ǚ́ҒҥҬѬҐ́Ҙҥ˾ȋ̆қҳ˶Ҟ̔̆ҡҟ́ҤҢ́ҧҾƺϚҫʀϏҍϖӃӁϑψҖϖӉӇϜҪҶϜҏҨėϟӐ"ϡӖӣϣҖ͌Ɏѕ͏͡Ϙ͔͖͘ȸш͜ХӭШͤȨͧͩͫћϕšϊѢϛʁ͵ɹηѫͿ5ΡʁΣʁϐѸͿѼԂȸԐΧʻԐ΋ɠΰξΓΕςΙάΚϘΜΛι7ԊИΛϐ7Χ7ӾȶτάҭĀμαԜε̙η̇τλԙνΑԶԞ̙ԌυϘ̚τӾϗԂϚƺӏϘϒՎӕԂ̩ϊ˿ά̼Ϟ́ϘӤԂ͈їϦϨϪĐϭЭĢsƋǲġАŻϺͿЋϿǑǬКĉǱǳǵǷǹɛծƭɯ8ժƷŉ0ղoМОȓȕɘӵЧЩЫդŊզuըĩșŲĲ֍ǇĻĽоǾǏėхȶӲȻȽȿɁɃ"ɅփӭԂ֧մІշУ֗ǉǒւքȑֆТȗ֓ƕȜƨǼȨȪǓȅ֝Ǎ֟ЕȼȾ3ɀՓЂЛ֩ւ֬նЈɘֽųȉֳȏֵРևЁƀ6ֻūȞȠȢȤȦ־ǍׁȳǍǕǗǙǛǝȀэ׋Ɇǫātɋ"єі͒ƺљɗͭӆӄėџӥԁӍʹӢʂ؇ҵӟʑ؇ҽәԍ؇Ӓ̘ԑ؅ʭӢ҂ӥԖؙӘ̎˅8Ҍӥԡ̾ҔҲ؏ҕأˍҸئ؎؀ˤӢԫد׿ӓԯӥ˷ӢԲѭү˶إحԺصت؝1ЙҼطӀ̡̝ؒՑ̙ؕ؜ӓӌӜӔن̭ՆӥϔӢՓُٗ؋՗ӥӡٝ̀Ӣ՝Өė׸Ӭ͑Ԃӯ͗ЎӲ͛"͟͝Ӷ֋ӹͨͪ֯ќԂ؂Ԃԁ؆Ϙ؈ٽιԉԈԌ5ԎԕԌԓϘؘԒӾ6Ԙ΍ԾορؠԂآˈηاҗΛԌǛΛԬԮϊضՅήԽԵγԝұτιȻɛԴԛڦԷ8ՃϐٔԂՑӈͿՋϖϐՏՒڶӗϓڹϙԄӣՙ՜٠՚ӧձė՟ϩϫգǆЯϴ϶ϸիВԂպЍۊ֦Ѓ׏ЇոЊƉϾջЎĲБրזźօיַɛ։ūٲמեϲےгֹœ۱Ŋֽ֚ǓртȰфǍڄ̥Ǖ60̇ԭ̚ǚױ֨٧׎Ѕא۟ǻ֘ČȁȈۨНטСУȘ]}`
        // , 'Delay Keyboard 1': `{"connectiăs":Ā1Č[ĀidČ0,āăąćĉnTypeČāhaĄel"},ĒĔ:7ėĂĦěăĞĠĢcĤĦĨĪĬČ6İęĆĈĴğġ:ģĥąĻī"ēČ8ŀĲŃĝŅķĹŊĩŌŎ:3őĚœĵņňĺĩ]ė3ĐĽ:ĖĘŒĜšŖŉħťė6ũōĭŬışůŕŇĸŲĻŦ"7ŷśźŁĳŔĶſŗų}ƃ8ƆŹŞłŽƌţŘƐĪ"nodeċ:đŸĕėtž"gain"ƧitlŢƫƭƯ"xĕ.52ėyƺ39832422586Ƽ0944ėaudĉNƟņ{ƜǒǔoParamValuơČĀƵƮū.480664ǰǈ0ǶǷ4}ļƥ:1ƧƩoscillatorƷĈƲŢȁȃȅȇȉƷƹǬ279șȚțțį"ƿǬ7ǁ7Ǐș089ǈ319ǑǓǕǗǨ"MONOľǱǆźtȕǙėkbMȱŇmăoƷŻłeǧƣȾɎļɐƃsourcɌĀǱǲ20ǨǺėADSRƢəȹɜȲrħeaseIĭ-1ɟ"_ƨƘtriĥgƳƷƠtuąȲsɖɞƜfɪqǦncȠĀʅcʇǚȯoǖƠŰŇɹɻnɽġȮǜǞǠǢǤǦɥ"ʉeʋeʍȠ11Ŭʀʂņ1.ǲ84375ɟŪŝ"ɷŢƠȆƿưȍĢ˃a˅ƸƺȗȜˏȚȞȠ0.ǁǃǅǇǉǋɜǎǐ"ǛȰƠɞʠĉʢǡǣǥɘ"ˉyTimņ˔ʼǻśĿˀƩˬȋƱɾŇ˹ėȕ˔Ǐƾƺ6ǈ93ǯ6ȩ16ʻ7Ő˟ʕʗǘʔʡǟ˧ʥ˪ˬˮ˰ƺ1ǈʽǼȞˁˈħˊ˺ˇ˽̦ˋ̀˕˶˓ƻ̟1ȫ14ʻǳǂ35ˤʖɃȾ̖̑ʣ˨ʦȲ̛˯˱.̠˴ĭ̤̪̐˄̨˼˫̫ȔƺƼ̃ȡȣȥ9ȧȩ5ȫȭ̀ˡ̼̔˦ʤ˩ʧ̝͆ǬǴ˳]}`
        // , 'Delay Keyboard 2': `{"connectiăs":Ā1Č[ĀidČ7,āăąćĉnTypeČāhaĄel"},ĒĔ:6ėĂĦěăĞĠĢcĤĦĨĪĬČ8İęĆĈĴğġ:ģĥąĻī"ēČ3ŀĲŃĝŅķĹŊĩŌŎ:11őĚœĵņňĺĩ]ė3ĐĽ:9şłĜŢŖŉħŦė6Ūōĭ12ŮĳŔĶŇĸųĻŧ"7Ÿś10ŽšŕƁŗŴ}ƅ8ƈźŐĘŒŰƎŤŘƒė9ƕČƋƘŠƚƀƜƑƅƊơ:ƣıƥńƧƂťƞ"ŝƬƮŁžűƏƃŵƶ2ƸƌƦţƳƝƪũ:đŹƢǃƱǅƐƄĪ"nodeċǊūƣtƛgain"ėĈtlţǟǡǣ"xƢ.559ǲǳǴǴėyǮ4374468085Ɗ638ƗaudĉNǖņ{ǓȉȋoParamValuǘČĀǩǢƭ.4Ȁ66406250Ȯȯ4}ļǌŜǤƛoscillatorǫǥǧĢȸȺȼȾɀǫǭȣ27ǵɐǳĖ"Ǹȣ8202Ż76Ǳ5ǼǾŭ"ȒȌȎȟ"MONOČȧȨɘİtɌȐėkbMɦŇmăoǫƯłeȞǚļʄīʄƅsourcʂĀɮ4ɘȟȲėADSRǙʏȧʑ0ɧrħeaseIĭ-1ʔ"_ǝƧtriĥgɄėǗtuąɧsʌʓǓfʠqȝncɕĀʻcʽȑȊɥǗƼ"ʯʱnʳġėɤȔȖȘȚȜʎ"ʿeˁe˃ɕŝƣʶʸņ1.Ȩ8Ǻ75ʔūƗʭţǗȽǸǤiǦ˴ħa˷ǬǮ24ǷǹǻǽǿȁȃȪȆȈˋoȍǗʓ˕̍ȕȗșțȝʚ"˵˽Timņ0ǯ˰ȴįˏƛ̛˾Ƀ˻˶ɋǹĿɔǮɜǰ3191ȥ9361ɓ˖̏ȏˊȓ̔˙̗˜̨̝̟̣̀śɓ˳Ģ̨ɂ˹ɄŇ͐ėɌ̡3ż̰ȣ5ǾȀȂȄȆ297̯̾ɹɴɣ̓˘̖˛̙͇̞̠Ȥ͋ĭ̯͎͔˼̩̫͒˽̭͜Ǳɑɐ̃ɖǼ8̹̻7əɛɝ̒ȓ̿̑ͪ͂ͬ˚̘ɧͰ͉ȣʩȳśɢͷ"ȡ͑˺ĢΠ͖Ǯ͙΃͘2̉͟ȅɗͤ8̽̍Ώč́ĉ̓ͭΕčΟǠȢΚŚźǜǞμΡ͓λǪΥȣ3΁ɑɓɕ̡˭̆Ϋ͡ȇ΍ˌ̀ϕ˗̕Δ˜Π͜ʹČŝȶƧΤˏͻΣσψϏ̡̂͛60̷Ά̺̼ΊɎ̥ͧ̐δϘηϛ̙ϝ̡ȪȬϟŜ͚ΞϤ̪ϧχ˿ͿϋǵΨ˪5Έϴ̲9ɟϫϷϗΑζΓͅϽσɍ˯ΛƖϢǨϨϥ΢ŇϤ͗˪ϫώ.̲5̴̶̸ϲαΎͨεϙ̈́ͮɧϾ.ŻР]}`
        , 'Phi Organ-A': `{"connectiăs":Ā2Č[ĀidČ0,āăąćĉnTypeČāhaĄel"}]ė10ĐĒĔ:ĖĘĦěăĞĠĢcĤĦĨĪĬ4į"ēĕėĂĵĈķğġ:ģĥąľī"21łńĲņęĆŉĝŋĺļŐĩ]}ėnodeċ:đŃıĳtŞōgain"ėxĕ.32ėyź1138069Ŕ6757741Ž"audĉNŧŌ{ŤƑƓĉParamValuũČĀųŵź25ƚƒƔoƖŨProĠrĈƧč}ŤİČƐŰĹōoscillatorŷ"ŹĲŻ9ǔǕǖǗ7žź3Ǝ420765027ż24ėưƕƗƨātǑĀvoƥmƘƽėADSRŪĀ48ǮrħeaseIı-1ƚ49ȂȄȆȈȊȌėǣȐlȅȇȉČȋƚ5ŕč"ȃșȒȜ:ȞȖďȢȤȚȓȝȕ"53ȘȮȧȩȲŁȬȑțȔȟ5ȵȦȾȖ6ɁȽȰȟ7ɆȯȨȱǢɋȷɎɅȻȥɇɍƚƉɐɃ"6ȁɔȶɛƆɚɈė7Įɟɂɤ"7ȡĀȭɩɗɥȫɮȼɌȸǦɣɱɫȺɴɕɶȱƊɹɷɓɽɠɪƌʂʀɞʅɰɷȏɨɖȸƄʉƚ8ɭȣɵɑʕɳʘɾʚė8ȴʐɿʕɼʝʆɺ8ɀʣʟ"8ʄʧʍȱ8Ɋʬɛ8ʋʱʑʳʏʌʻƚ9ɧʾʤĬʯʔ˅ʵ˃ʭ1ʸˇ"ˌʽʺ˄ˏˁˎ19ʗɯʿėŔˑ˚˓2Ŕˎˡʜ˟ʚƚǳǵeƳǷėMONOČ6˴Ǟĳ_kbMǭōpǴſėsourcƻǿʋȍʽȟ˂ȟɭȟɳȟʢƙȖɼȿƨȟʄɉ̘ėɏƼ̝̝̚ˉɘ̝̉̋ɥ̍ɥ̏ɲ̜ɫ̓ƚƍ̭ʁ̟ɫ̡ɫ̣ɥ̥ɫ̧ʮ̩ʮ̫ʮ̑ʠ̯ʠ̖ʠʫ̔ʮ̶ʴ̭ˍ̴8̼˕̴ˌ̶ˌ̸ˏ͎͉ː̭˗̾˗̀˝̭ˡ͠ˡ̘ƚ̃tputŪ[Œ_ǂŌ"sŵġėŨtuą̭fȃqƦncſƼƯƜoƞƠƢƤƦǾ"ͽeͿe΁΃616.ǥƃˌ3ǣ1Ȁͷe͹ͻĲ΅ƱˬƵƷeƹi̇"˹˻ŨĢ˾l̀"ͱĢʹͻǸƿ:ĭėηǄǆǈǊǌǎŸƬǩ"΃0ŻǝǟǡǣΙˡωǫƲ˼ĀćǱ"˩uǶͦǹǻǽǮȀˎȎˎȗʶɪȠϧ˥ʙɛȳϧʦ˦ϯ͈˒ʭ5ʰϳϪˉ϶ɡϵϺɺ˴ˎəϩЁʹЀȸɢЅɷ˂Ͻʇ˙ϮʇϭʞɛɸЋʀϲБɺ̳ˊЕϹКɷϼЈʊˎ7˞РʳЍУʕАДɪ8Гʨʒ̓ЎʩЙЮʩϿШʕПиʒТлʠЇсʮЧоȱ͒Нɪ͔˖͌Зƚˌучѐ͐˖щеȸ͟ˣ˗ˣˢя˜ͥя˨Ǵϝ˫ϗƚ˯˱˳˵ǟė˸˺˼"γε̂̄̆΍Ϥ̴Ϧ̴Ϩ͉ϫѼ͂Ȳ̈́ȹ̭5͈̙̞͉҅͗Ђ̴ЄҌ̺Њ͉ɦ̲̀7ҁЖғ͆ɫ҇ɥ̶ʈ̴7̺Ц͍̾ʖ͍ҁʡ͍қʪ͍͙͋͗ʕ͑͞ˆ͓ю͚ұ˅̼͜͝˘͢ќ̴ͣ͢ѡƙͧͫͪͬĐͯπͳ͵Ǐ͸ͺ˭Ύ;΀΂ϟƛƱΈơƣƥέΏΑΓČ401.ȳаƍƌƅа3Π΢Ō0ΥǬƴƶƸƺ΍ίѱѳǏӌιġλŭČΞοű"ǅǇǉǋǍǏǑό҆ǗԐǕǚǒǜΞϏǢǤǦϓǪΆˬǮϙǮϜϞ΄ϠǼѸђвȱѻъɺѽјȱѿԬȸ5бʲ̒ϱϧкѓɄϧрԻɜԺԩɘнՂ̢ЃԨԶ̦ХЪфɬХԵ˛̮ХзՅҜХՄՉ̷ХՈՑҤџ̽ˎҧ՟аաдЫͅաՁՙҵԲʳԾՕ͙ԯҲˎїէ͘՘Ց͖э՜˓͛՟ҼտҾ՟͡փўխƚˤʔѣ˪Ԟ̴ѩ˲:˴6˶Ѯӹα˽˿Ǐѵ̅έѹ͉ԫ̌҅̀Դ҅҃5қ̶҆҅Ƌ̭ҋՃ֭Ҋґ̼ҔҡҖҘ̱҃ҡҝ̵̲͗Ң̲̼ʓ͏̀դ͏҃8ҬֻլʕҰ̺ѕ̴щє͕ҷє̺վ͚בĬւ͉քלֆֈӄǸԆӇͫͭӋԅӾӏΡӑͼӔΒӖԤӘƝƟӛ΋Ӟ׮ӡ:945.׈Ε˗ˁΖ9˴Ӯ׬ΤԜΦƗΨӶάӸѰ֗Ѳ֙ԄǃӍκƾԁ:ŔؔͲԇσԊφǐź08ԓόԕ˶ϐԙǧϔԝϗǯϚԢǷƚǺԦϣռʭԫղȖՌԿԱػȲՐ˓ϰ՟֧ԹϧոكկՙҋـҍևՆ՟ɝЃцՕִِɫЭٖقʭҙـֹ٘Мٟىًٝ՝ظЕٕիؽհٚիٜʷզф׈թա٤ʷ٦˓ձն׏٘յфьտҷـёэ٪չٿԿњփӀ٘ӂօٰɈ֋ѥ֍͉֏ѫ֓ѭ"ѯΰͲӻ́̃֜ԧ̭֠ؼ֢҅ҁلѾֻ֨ϸ҉ֻُ֭ɘֱֳ֭̾Վҡַ̲қМ̰ҟ־ңׁҦׄҩׇ׉Ү͍׍͍ҳ͜׋ˈۍזٽѐי˔͠ڍנͤ̑ӆͩץӊѮӽӎ؆Σ͉ӟӕ΃Ӆ؉׳ΉӜΌǮۥׯ΃2Ε.6ƭϸȳ0059ʴۢӰӲϖӴΩΫέ֖ڞؓζרӎƽţ`
        , 'Phi Organ-B': `{"connectiăs":Ā2Č[ĀidČ0,āăąćĉnTypeČāhaĄel"}]ė10ĐĒĔ:ĖĘĦěăĞĠĢcĤĦĨĪĬ4į"ēĕėĂĵĈķğġ:ģĥąľī"21łńĲņęĆŉĝŋĺļŐĩŒ23ŖıŔřňĜĸŌ"detuąŢė2Ł:đŃŧ3ũĚŜŬşŏħŴœ5ŦČĭŽśūŞōůűųĿœ6Ƈ:25ƊĶŝĹōĻƂőŵ7ƕ2ƙſƍŮŰŲġƒ28ƣ7ƥƌƜŎĽƄ29ƕ14ƱŊƳƏƪƄ3ĮŸİČƷƼƛŭƞƵĪ}ėnoůċǄźŅ"tƧgain"ėxĕ.3Ƥ"yǡ1138069Ŕ6757741ǤaudĉNǑŌ{ǎ"ǸǺoParamValueǓĀǚǜǡƗȀȂǻǽProĠrĈȎČǿǎǅƖėǘƳoscillatorǞ"ǠĲǢ9ȷȸȹȺưǥǡ3ǵ420765027ǣŶėȖoǼůȠātȴĀvoȌmǾ}ȀADSRȏȀɖɘeɏɚėpȭyǜgKeyɡėsȯpLaɳNSourcȟŸŒ_kbMǽČtrȍė_ȦŭsǜġėƿųčȀfreqȍncǦʕȕǹĉȅȇȉȋȍȏ"ʗʙʛʝČ616.ɈǪ183Ɇƺ8ʒƩʔ0ʠȃɦșțeȝiɿĀʃʅɐ:ʈʊǗƧʏƑȢǕ:ƉˏȧȩȫȭȯȱǟȓƻȽȵȿƺɂɄɆʳ2ɋȁʡɎʆčɒɔ"ɣuəȠɛėɝɟɱ˲ɗ˴ɥˮǿɨɪɬɮɰ˶ɲɴɶɸɺɼɾǓ[ʁˉˮˍeʋʍĢˑʑƨƐɧʩʘʚeʜʞȡɌˬʣȈȊȌˇ̞ʫ̡ʭ:401.5ǪɈ4ǳǬ8Ťʻ̜ĕʿȗů˂ȜȞʨ̒ˋ̔ȥːʐĩ˓ŗƺ͊˘ȪȬȮȰȲȴ0̴5Ⱥ͜ȸėʞ͙ˣɁɃɅɇɉ˩ˠɍɦɑć˱˳˵ʟ˸ɞɠ̇˼ɤͫʕ̂aɫnɭɯ˻ɳț̊tɹɻɽɿ̐ʋ͇Ō͉"ʌ͋ų̽ǀ͹̢̬̠˶̀ȄĘ̑ʦ̫ʪΖ̯945.84ʯ1ȷ̲ǭ66ΒʽΙˁȚ̈́ˆ͆ʄ̓ʉ̕˗ʎ͌˷ȣŨλĢȨ͓˛͖˞ȵ0ʺˡ͡ɀ˥ͥ˨˪ͪ̀˰ɑͯɚɜͳ˻ϖ͸́"ɩͻ̄Ϳ͵΁ɵɷ΄̌·̏́ϫȢϭ,ǿ̑η͈ι̖ΐ̚ʓ̝Οʬ̣˷˫ȃ̧ʥ̪ʨϺ̮ʞ2ʯ.6Ɨ5Ʌǂ0͛8ȼϸ̥̿ˀȘγ˄ͅɑ΋ʇϴρō̙͍ϯ˔̼П"ȑǝχ͙ω͟ǡЌ90ȿ6ω378БɃЕ̝́ɍЀ̩ʧɑШƈ5αЗ˃˅ˇξФˠ̗ōσ˚͕˝ȳǡЬϋ.79έ4Φ51ɉ0ǵ89к˭ˋĀͭϕ˽Ͱ̤"˹ʹΔϛ̀Ȁϟͼ;̆ΔϤ΃΅̍ΈϱˊŌfȋsκΏƳСίϹ̟ϻϣɗoϨɾΘѤоΝЃҊЅƈ҈ДϾл̓ЙεЛϲҀ҂κэ"СъŗƗ͑ŭтЪʲˠ̴͠ǭбΧджиȼϒѦΙғЂсǛǝƖʾѤβчКͱοήЦя͔˜͗˟ЭȵјњќўǂѡѣқѥǾϔ˯ϖґѭϙ͵ѱһͺѵ̅΀̉ϦѻϩĐѾˮҁl҃ϵ҆͌ҙΔЄΗѸҍҏϗҒΛЁр˯ӹ̯̳Ǩέǣз009ǨѡӷӃӚӅδ̫М:ӱӳЦҧ͎ŧȼҥҭѓˢ͝ԣȼұЯҴгʶҷ7йԒѲӿʤп̫тƖ3х͂ИшɡԜǆϊҥӌυђ͘ȶԣ͜ԥǡӓ6ћΣӖѠʵәҺӜѨӞѪӾӡ˺ӣՕϜѳ̃ͽӨϣӪ̋Ά̎ӮΊҡČԘ҄ҥ̛҇ΓϝԄϼɲӼգՖнԀԲҕ̭Ӻ̳Ŷ68վ9заǬǪˠГĲԷeҝԺҠѿըңҫ̘νԼƖәԟӀӏȵ5͛Յȹӑ͙ԧвҶзԬҹˬ՛԰ΜҾ˯ԴȔӄцԔԻУŗǂ֑ю˙Ӎφԡ֠֜֝ȷ֟їљՊӕџӘ֯ѦӝɕՕӠѮϚ՚ԯϞ՝Ѷө΂ӫӽ̏ӯˋթӴμΑխʔկҖӺϝsճѼӠնԱҔɑհƈȶ˩΢ԍ̲7Ŷ4ցԐ։֋Ӈˈէԗ֐Ԛ֓]}`
        , 'Sequencer 1': `{"connectiăs":Ā0Č[],"2ĐĀidČ31ēĂĄĆĈăTypeČāhağl"},ėę:32ĝăąćĉnģĥħcĩīĭĒ"1ď:[İĚĜāĶĠĹĻĦ:ĨĪąĬĮňĲĴŋğĸĢĤŐŒŀ}ł14Ė"ĘŉĵśġĺŞĽĿŔĭįŧıĳŪķŬŏůœeŕł21ŦŨĲŊĞŸŎŮőľżŕųƃŶŚƇŝļƊŰŽŁēěƂı0ŷōƓşƋšłĳƛČƝƑƟŭƔŠűŢĮ"nodeċņŗƨtƉ"gain"ēxƧ.36ēyǄ1138069ƀ6757741řaudĉNƳŐ{ưǛǝoParamValuƵČĀƽƿǊǆ20018952970986ǣǜǞǠProĥrĈǰč}ŖŴČřƺƬoscillatorǁ"ǃ:0.443946303Ȩƀǹ5ǈǄ847Ǻ427ĳǎǾ83ēǤȇƴǱātȤĀĪǭyseȡȐēvoǮmǡȑɓɕuɗǟɆɒ"pȝyƿgKeɎǱưsȟpLaɬNSourcȏđē_kbMǠČfǭɏɺȖşsƿĦēƴtuąɪēfreqǯncǉɠsɕoɳɵɷɪȅǥǧǩǫǭǯƶĀʑʓʕʗČ616.ȼǍǺ35ǹ48ʊeʌʎȥʡɅeȉȋɐȎʨ"ɼɾɟʁlʃ"ʅħʇʎəŗńēːőȘȚȜȞȠȢȤȦ2Ɂȫȭȯȱń1ȴ"ʘȦȷȹȷʳˢ0ɀɂ"ɄoɞǡɈɊ˶nɍɏɑǢɚɖɘưɔ̄˹ʏɡɣɥɧɩʙɭɯɱʝɶɸłɻɽɿ:ˌˎ_˘"˒ʉ"ʋʍɘʐʒʔeʖʘ̠̂ʛ̔ʟȐˀǦǨǪǬǮȏʩ̨ʬʘ4ǹ.5ǍȼȸȀ682˵̤ʾ0̳˹˃Ȍˆɇˉ̜̚e˗ƻ̡ĭȒƃŤ͗ȗșțȝȟȡǂǄ6ȯˤȮȰȻńȁȵȥ.ˮȺ˱ȿȂ˵˷̉č˻ɇɌlɎɐ̊̇ɜ̅̃΃͹̭ɢaɤnɦɨʨɫ̑ɰtɲɴ̕ƶɹ"̘ˊŐ͕ʄ͘ʈȢ̦͊"ʪ̩̫̊ʚlʜΕ̱Ǣ̳ʣ̶ʦ̹Τ̻̪ʭ:ȫ5ͱȬǋ99ǹǐ6Ǉ̣ʼ̥Ƨ͍ȈȊ͐iγ͓ˋʂ͖ˏΟ˓͛ıƀ͞ş˚͡˝ͤȣǊ͈ͩ˦ͬʸ7ͯ˭ȸͳȽ˲˴ɃȆ˸̚Āć˼ͽͿ́̆ɛɗʠ΅ɝϰưΉ΋΍̭̏ɬȋ̒Γ̰̖ɺώΜϐΞƬ͙ʻʽΣΥ̼Ψ̯ά΄˶Ϯΰʥ̸ˇДζʘ2ʯ.62556́Ǹ5ȂϥτВχϭǥ͎ϊ˅όˇЋʀЍϒЏΠ˔ȓƄϘˑubgǩph-ɏΦɷϝˠʲ7ξѓєѕЯˬȧШ2ȼ͆ǓȯȁЪгˁɇϲͼ˾;̀΁ϸЙ΂ϼɟ̭nStepƶσcɵʒntѲѴČ˪ɬǨtTiϹȥēƲѳ҄҆ǌХςҏҐҏȽēsхǝvʮҔѳpMȞri˼ĕņΝtrǯ,Ɲҩ,ҥҧƝҬ͖ΝΝҮҦeţŅ[ƝҤҴҨҫһұЍҳҭҽҭţťņүҼҲ,ӊӈҪҹӀſƁņӎӃ͖ӏˍӖӋӀӕҼ0]ưmuѳdCƖĬɠisP̌ΌČӈˏickǄ3ӵӶӷӸ˵wƿdowIsOĥǀ̛мHTMLGҟı̭ԇԉBoxγҢĎ̊Ӓ̭ԕư3̊ӆ̭5ϺŃŅԖɠԘưԚƙԝ̊Ԡ̲ēŤɇԣưԦēԨ"ԜɠԞưԬήԴԘ"ԱԮ̊ԵԷ̭ԹēԻȑưөIѱyʖлӘɃdsrՌƴˠĝӦDȞaɇԕ"ѭŐŊaՓ϶ԲԣՠѫČգեԡԯͺաիՒՔԡƀɇձ:լմ̲əКʢ̵Нʧ̊͸ω˄ȍиɇҕbҗҙŧsՌSՎcՐˎѱқѶճՕn՗χϕĚȕ͘хчaщыʫζ΀ͥͰȨϦљǽќȃȀȮ9ѡվѣͺѥͺϴѩɠոԼթ̈Ͻ҈ѽѵČ4ĝѹ̪ѼқȔҚ҂ҋŐƨ҉eאիׇ̠ҖiҘ:řɬѴҝҥҠ՞ĐҺӂӞԮҷӗʃӍӅĐӍӚՑקĔӒ[ӊӁҵӠӢeӤӦ̊өӫΊɥӮһӰӲղ"ӻ֛ӾԀԂ̪֔ϑԏԊԌ̊ؑԑԓˇ՟ՀŃՂ̊Մսń԰ԗ؜ɠ؞ԲԞԿآɠՃյԾؚԳĔ؝ʠՊ֏ՍՏԅՑ˶եՖe՘ƭŽ՛t՝ͺ՟ոպզרշժչ֙ծامٌԭ׳ى̄؇դջήս˷М̷ւɠքƴ͏зγ֊֌לēՋص֓ط֕ׄƶחٖ֚֜ʿƯ`
        , 'Sequencer 2': `{"connectiăs":Ā0Č[ĀidČ37,āăąćĉnTypeČāhaĄel"}]Ę2ĐĒĔ:31ĘĂħĜăğġģcĥħĩ},İĕ2ĵĚĆĈĹĠĢ:ĤĦąŀł"ēČ4ĴęķŉĞŋļľŐĪĬ"1ď:đœıĳņřĝĺŌŎĿĪŒŔĲŅŘěŚŭŝŏĨűŃ:ŖŪŷŬŜōĽŻŀš14įŧĕŗĶƂŊĻƅŞżŁž3ŵƐňƃƓůşƗƍſƏŇĸśƞƆŰīĭ1ƌųũŶƜƒŮƩƠŲŨƚƥŸƄƟƖƷŕƤūƳźƪšĳƮŨ5ƁƲƧƴƕƈĘƙǈĕ3ǋƦŹƔƇŠǑ3Ǔ:0ǖƻƨǏǛ"3ƋťƘǕƱǗƼgainǥ35ǞǠǬǢǎǚƫǦ6ǞǴǡƝŮpĦǳ7Ǟ4ƹǂǍǄƠǆ8ǶȁǃǙǅǑ9ȈǷƛǭǣǻš4ŤŦƯ8ȒȌȔȎĘŖǿǫȚǹȍƖȞĮǩƢǧȤǘ"frequencyŠŁ"nodeċȲųǷtǮǰǲĘxČ0.279ɗɘəəė"ɀǟ.16874ĳ69398907ŗaudĉNɅŌ{ɂɰɲoParamValȼɈĀǯǱɒɠɡ18605238085815ɸɱɳɵProġrĈɇČɷơųŵɌƞoscillator"ɐʉ44ĘɞɓʕǴ519125ɢ306ĘɹʜɆʥātɑč"Ħʂyseʵčɂvoʃmɶ}˛˝u˟ɴˍ˚ĘpʱyǱgKe˖ʥɂsʳpLa˴NSourcʤťš_kbMɵČfʂ˗Ę_ʪŮsǱĢĘɆtuą˲ĘȸȺȼȾɞɷĘs˝o˻˽˿˲ʚɺɼɾʀʂʄˎ̚ȻȽȿČʎǫ̖̔Ō0̨ˌeʞʠ˘ʣʅ"̄̆˧̉l̋"̎ģ̗̐ˡƿ:ţĘ͋ōʬʮʰʲʴʶ"ˑɓɕɚ͠ɘɜʼ.ʾ5ˀ˂˄ˆˈˊʛo˦ɶˏˑĀ˔l˖˘̘"˜˞ˠˢͼͰ͹˪aˬnˮ˰ʅ˳˵˷˹̤˾̀[̂̈́̇:͇͉̍Ƽ͍̒"̷̗˨ȷȹ̱̝͹̡ḷ˼Ύ̧̩ͭɽɿʁʃ̀Ā̰̜̳ſ01.5ʒɕ477ˈ8ʑ̓e̕Ν̺Ϊ̼̾ʡ́ˎΒ͆̊e͓Θ̑ĪʧıƊϑʫʭʯʱʳʵʷɟˉɝʉͦͨ˃˅8ˇϡˋͯΓĀćͳ˓n˕˗˙̟ͺˣ˟ΩϷͿϭɂ΂΄Ά˱Ξ˴ʠ΋t˺Χ˿Ɉΐ̌ύŌΕϐ"ΗƞΙ͛Μˠ̙Πγ̞˳̢΍̦˚̻ɻά̬ί͂β̲ɞ945ͥ461ˁɬɡ96ϡЗɒТͰὼiΰ̓̅ΓАϘ̏ϓ͏ž2ŗ͔"͖ϛ͙Ϟ͜ʉ˃ʻϣιͧˁϦͫϪͮ΀˒ϯˎ͵ͷϵ;ˤͽĘͻѥѝ϶Ͽ˭˯Ђ϶Є˶˸ЇПΏΑсώ͈БГх̗ςτИΟ̛ЩΣОЉѦ˓̪ͮέ̭пШ΢:2а.6˄˅ι0ʏɪɜиǟкʝʟϊо͂Ў̈Ϗф͌цϕƎҨōsubgɾph-˗Ρ˿ѐ͝ɔɖͣ͡͠ʉҕ5ɨʓɧщ6757ȣ҉ɺѪͲѠϲͶϴ͹ѨϹСѧϸeѪɂnStepɈϡc˽ȹntӟӡČŵ˴ɽtTiӗǷɄӠӱӗƙ.3ӻӼӽӻŖʺ"үbɲvČѓԂӠpMʲriϰȱ[уtrȼ,ǠԘ,ԔԖǠԛϐууԝԕeƉȠǠԓԣԗԚԩԠҧԢԜԫԜƉǨ[ԞԪԡ,ԸԶԙԧԮšщĐԼԱϐԽѺԷԮՃԪ0]ɂmuӠdCǤΞisP˫˭ČԶ͊ickђжաբգжĘwǱdowIsOġǲΔҧ"HTMLGԎı϶մնBoxпȱĎ͹ƭΞւɂǝΞǨ϶ǵӘŢŤփΞօ϶ևǑ͹֋ɂ֍ʦĘƊˎ֐ɂ֓ɂ֕Ǧ֗͹֚͏"Հ˒֟֜͹֣։϶֘Ę֧֨ՕIӞyȾҦՆ˓dsrַɆ͝ĵǏDʲaˎւϻѥԇˊ־ѣ֠֐׋ӗɯ׏Ϻ֝˒ӖŌוֿϺ֪Āך׍ֽםС֨ϫҋХ̮ΞϫлҡнпԃԅԇŵֶָֺձּӞԊӣ׎ֿׁe͝чȳʩΘҰҲaҴҶ҃Ⱦ͸ϟɓʹєϠ˄ӄˈ9ӇӉӋχϬ˧Ϯːӑϳ͸Ξס֎ךӜĘ׺ӡɈԁӥrӧөԊעӮʢӷ̹اoӶӲŌӻ̠Ұײґ̠ԊԌԔԏ׉ĐԨ԰Ջ֜ԦԹҧԻԳĐԻٌՆى֩օԒՈԯԤՍՏeՑՓ϶Օ՗΃ՙ:՛Ĉ՞עէnթիխկֻ͉ռշչ͹ٲվր͂׊֬Ţ֮͹ְ֨ţ֞քٽΞٿ֠֋"ٻ֡ĭپמ֓ډڃֆڍץĘ׵SֹcٰБa׏׿׃ƽl׆t׈˒׊أלאيˎڧ׽کŢڈڬףڮןדכڭ̧צҊФήת϶׬Ҡ̿ʢңˎױiԆؿœsַڗ׷уɃӪӢŕڭڞйҫĲǫыʇɏёɟؐϢɟɩϨ2ȉ˄ʍʐ0Ыԁڿ؜Тרڼпۚʉʙؚ׭ہϋӘƘԁыэ͘ϝ͛һϡͤۡƙۤʖ6ۧ۩۴ϭӐ˒ѡӔآӚϺإϽ˩՘΅ѮΈـЅѳЈ̥ѶЍѸЏղѼҩѾΛσ̸͹ҏδѰ҆ܞϺקڻҍЧК҄:ǊܧҀй܊Ɇмۂпҥ׸͉ыЕ؂ƯܸыȄħҺʉ͟ҾɚӀ۠ɪ܄2ۥ܇2ۨ۞۫ҁܱ̫ۯܻ͂݊Ӎψ׮ܿΈۖ3ϡۻϚ۽͚؎ɠŵ܂ݓۣݕ܆܈ݚќ܋џ܍ӒѢӕܑؤӚئ"Ѭܗ·ΣΊܜѵЋѷͅܢּܤҮϓѿܩΞܫМ̠ܮΨ֎ݝҌЦ̯ܵҐ̶ܨυҟܽݥ۷Ā݁ێ݄Ҫ͐Ėҭܧ˫ۿʸԁͤ1ξɮ0κˀݩаŵݛ͹ޝשпɆ˫شԇަ̽ިۃ۸ȳӌ݄؆ҳҵҷγ؍ۜɓӈݏɚؑ͞8Ь޸ˇŖɫɥιܼͱݻʹݽ܏϶أ֛ڵރبۑŴĵӦȽدӫĲـӯ߈ǟضظӸ2ӺӉؼԄۆԇϡ˴ӡقԎϰȟِԩٙԪّԶࠕࠑՊՇՆԭՆԶهԟٍࠗࠝࠠԖԸՂࠖȼՌĘՎՐՒǚՔՖܖg՚ԩ՜٨ɟϦզըժլծȽښĘٲոųջյLٷпࠏ֫ڑ֔ړֱ֦͹ǾΞȇΞȐΞȗ֒ڊڋŢ֣1ٿֲ֜Ţ֧֜ࡑ϶޸քࡕࡥࡗ֔ٻן֢֣ʑ֮ࡠ˄֮ࡤ֢ࡓ֔ࡨ֢ࡪֈٻǇڔۉۋژ࠳Ԗڲ۔߾ڠڢڤĀࡉנހڨڸۭܲޟ׫ݹާ۶ߍĀۅۇɡڕۊ׶ڙ٥࠴߲Ɉƙۓ٫؀ەޯ9ޱۼϜݮߘ.ӉߛəߝͥіϥͪϨͬݣ؛ߨ؞ݼؠѣәͼܒނܔބ࠱ܘވܛΌ҇ތܠގ࠿ВыكĦglΚҝ϶ޗ҅Υѵܰںݞܳޠ؋δ5Ƿҝφࢼ۵Ң݀ܡ࣒ࣔԎࣖࣘϔ͐ȟޱ۱ݯࢲࢳɗࢵ˅ɬǧʎϨӋɣɭߧ߂࣡ޞڽ"۱ґθߊܾީ݆ıƀ͊؅ұߓ؊Ҹߗ܀ࣾɧ޻ЯʔĖ8अɜ߁ўࢿߪࣁݿࣄށϼ۬اېࢤߵح߷ېرڣسعɒ߿e߽ӹդुʍࠅؾǫࠊԋԍلڥنࠣՄԥՁْ̋ԞُťّАԿٖࠥࠩ"ࠫٝ࠭Ű࠯٢ЀࢃБ٧՟Ϡु३࠹٫࠻ٮ࠾݂БࡁٴΞٶտցڂ֒ڄ߯ځࡊॹڒ֎ט֑ࡥॺ֨ڴڊ঄ֵ࢞یࢠێڜ׾ࢧڟƵĨࢉمיࢎڷঀגڱ঎ڮঁڵעজڎګগڲ࢐ؚۮࣣ࢔ӎۀ࣭࢚͂ĕ࢝ࢁۍղࢣরࢅঐࢩžȉࣸɎ޴Ϡࢵ޸ɭţ޼࡝жԈधھउ߄͂ऍʎ࣪ݛऑ࢘ˡՌ`
        , 'Sequencer 3': `{"connectiăs":Ā42Č[ĀidČ48,āăąćĉnTypeČ"gain"}]ę43đēĕ:55ęĂĄĆĈăĠĢĤchaĸlĪ,ıČ56ĶěĹĞļģ:āŀłńņĳĵĚĸĝĻġŏĥħĩīĭ4İ"ĔĖ3ŊřĺğŜĤplaybackRatģš"45ŤŦ:ėũĜūŎľŒąŃŻ46ſĲ47ƃŌśĽŐĿŁƉĪĬż7ƎČ0ƒŚŬƕőƘeƊƛėƞƁŉŘƄōŭƖƈƧƚę51ƫďơƅƱƥœŻĴƹ2ƻưƤƗƿƛňƫƷǄƔŝǇƙī}ęnodeċ:ĒťĲƠ"tƽĦĨ"ęxƟ.279ǫǬǭǭƑ"yǧ341ď07650ǩ3224ęaudĉNǖŏ{Ǔ"ȃȅoParamValuǘČĀǢĩ:0.1971539Ǽ5ǫď805ȋȍȆȈProĢrĈșč}ǓŕƺǟƽsubgȒph-seqȘncerǤ"ǦȞ.4ȁǱǧǪ66ėŽ1730ǵ89ȂȄȱǗȚātɓĀŁȖyɉɐȺęvoȗmȉȻɵɷuɹȇɩɴ"nSŹpǙ1ƭcurrentʅepČĘ"stȑtTiɹƟǔoŹʜʞĳ1ęɁbȅvČʉʧʆMŸriɭ"ƷđƠtrȘ,ʸʺeʼ,ʹʻƠʽʻfȖɉˁʾˀ˂ʿˇlˉˍʼǉžǚ˒ˏˑˋ˅ˎˈʿ˒˄ˊ˃ˡʿ˛ˀ0]ȋmuŹdCƳŃʂisPŰyĨgČ˒ǟiŵǧ12ŗwĨdowIsOĢȝ˘ʿ"HTMLGʲĲȊę̏̑BoxȹĀʶč"0ȚȋƸʂĐʂįʂţʂ˕̖"ƍʂƝʂ8̣ę9̵"1̢ʂ1̥̮˿̸1̩̫̭̿̿ɻʵ̸̡̧̭̮́̓ȋͅȋ͇ę̴̰̮̲̮ʂ̷̼̻̤͎̤̿̾͐ęǶ͇͈́˲Iʄyɍ˹ˋȌdsrͫǗɓǞǐƧDŸaɪ̟Āɶɸŏʦͱͳ̣͓͊΁ɾ΃ȂͲɳȊȻȯɧȏȑȓȕȗ̝ΒȎʀeȳȵɏȸǙĀʨʪʬƭͪͬͮ:˺ʄʆʈƭaΎ͵eͷɻȽŨȿƤbuffɏɑͷ.7ȩǮυǫęǲɔňȧǴ60837887ǸɦΛȈɪćʴɯlɱοʂΊʤΐɼ΂Μ̸ůű˷Keɱ̸ʘȵLaʘNSoʌɎǙ[ƛ_kbMϙ:̌ęloȵͯʻ"λνɏϬωǞǗtuąϨ˵ųŵŷŹϯɷo϶ϸɺΚĉȐȒȔȖȘ΢"ϩŲŴŶŸŏʖБГŏ-͂4ɕǹň̀СoΜΞȶΡɪϾЀʁЃЊμξrЎƟζǜĖɗǠƤoscilŰtoɐǥəτφǮψə9ɛɝƷɠɢ1ɤϗɨȉɫϜnɰɲ̸ϢРϥ΋ϧʂЪϫϭ΢ȋϰpϲϴОrϹđϼтЁх_ѐŝsĨģęбДʂfʎɋʏcω̮sМ҂Ɏ·ѪΔФΗЧɪҔɊɌҘʬ1ς8Ѩ8Į3үďȡɥ"ґŏ0лнȴпi̝"҇ф˝ęҋĤҍДьƀŽӄƽђєіŸљπǧǩўυǰЏ.ϋ0ύϏϑϓϕǰȰмЁĀϛɪϝϟΏȋѳҟ"ѳѷ̮ѹngЎѼʮϱϳtϵϷ҃ȹϻęϽϿ҈Ӄ"ҊƽʹiŁglҏҶeВҒ̮ҦҖɍҙѽҜӽҞȺлУΖЦҿԔҨω̽8.Ǻɢσ6ǴȭǬҐԐвыҠһΟȷҾШӁŏхӅŐԉԋԍĪȼэƬӌƤʨɄaɆɈҧҗοћɔ˿Ѡϊ6όƌӞϒϔϖȌΓӱѭӨѯϞѱϡɽϣ͈ӰӥȋέʓǙǃāʌʎʐʒʔȞʮʚʣҸʠʢʝŏǌʗɂΥƁʮʓʰԉʴƪ˖ˋˍ˨ę˪ˬˮƦ˰̮˲˴ϪӴЈ̍Ĉ˽ϊę̂n̄̆̈̊Čх̸̘֥̜̒̔̚ШևĀ̤͞·ȋΨSͭc֣ԅαͳγͷĶ˯ͻʙɪ֭ӯդΌ΅ӫΑҠԞХΘӷ՛ϘǗоΠԷɪΤiʫցťsִͫΪхժʇČխֹʹ֞δыՂӊǰԼŞǣՏȟՑɘɔǴǶ2ǸԨǽǿɗӣӱԝΕ׋Ҥ̠Ȝǧȧ8ȩϑǻ0؉؊8ҺȲҼגΙרƏʖ׫؂׮Ƞխәɚɜүѥɡɣҵ׻ը׉׾ңҿ؂ɔ749Ȭƌϔثǭ،Գ؎ԵрԜŅՃս׫fѕŹњɒǧƭәӛӝϐ՘ӡسʁ̮ӣ׊ئШԢҗω95ς3ԫ9ǶɖجϓʖQʬęبȟŗҷԲ׎ѫבԶҿ׫highpϳċӉĲĴՅŝؖـɔقѡѣ؝ɟ؟Ѩء՜أ٦ҡԟ׌ɪب-٢؍א؏٩ѼؒŇƭػؽՎٹȟٻײǵǷиǼɠ׹ىɺؤҢԠُҕԣČ9ұٕď3ȥԭ67խٞ:΄١ӚԯԑҸڍΝڏضĀ׫Ѕwٰsٲǒ`
        , 'Metal Lead': `{"connectiăs":Ā1Č[ĀidČ6,āăąćĉnTypeČāhaĄel"}]ė4ĐĒĔ:1ėĂĦěăĞĠĢfrequencyĩ,įČ12ĳęĆĈķğġ:ģĥąĨĪė5Į"ēČ4ŊĵōĝŏĢcĤĦŕī"6řś:7ŞĚŠĸŐŒŦĩŨ7ūİ0ůŌĜŲţťŔŶė10ŹŇĲĘşžŢőŤœħƃ"1ď:đŚİĖƊŰƌĹőgainƒňƇıƉĴƜŎƞ"ƠƢŶ}ėnodeċƖņ:Ż"tƍƭơƣėxČ0.ň0ǈǉǊǊƉŃƺ.426631578947368ŝ"audĉNƴŐ{ƱǡǣĉParamValĿƷĀƮƣǏ480Ǔ4Ǿ25ǋ04ǪǢǤoǦƵProĠrĈƶČǩƱƹƉƽƬoscillator"ǂǄ.ǝėǎǅǑǓǕǗǙǛǝǟėȈǥǧȔātǃčǡnǴyseȤčǪvoǵmǨ}ɆɈuɊȋɋėpȠyƢgKeɁȔǪsȢpLaɞNSourcȓƸȖɬŅɭǩɮɱɰɳɯɵɲɶǩŨ_kbMȸ:trĿė_șųsƢġėƵtuąɜėĻĽĿŁǎȕȵǬoǮǰǲǴǶȹʒľŀłČ8ʋeʍʏƺȇʙɑȍȏɃȒǷ"ɼɾƵČʁʃƼƾʈʏɌŅƘŜėʆĢǹȥ"ȼȬǠȫǐǒǔǖǘǚǜǞǠȶȊɿɰǫȉʛǱǳǵɪǸǀČ23ǆȀǈ2875ʬȉʮȎȐʲɜȖˁ:5˃ƾțȝȟȡȣˇˉ.5ŉ"ˌȭˏȰ˒ȳ˕ʭ˘ȺȼĀĥɀɂɄ˙ɇɉɋɍ̗ɑʐ"ɔaɖnɘɚǷɝɟɡɣɥɧɩƷđɸ̮ɷ̰ɴ̱̯ɹʄʵɿʹeʄ˄ősľǯʊ"ʌʎɒ"ʡʔʤɅ˭ǭǯ˝ʞˠ͆ļʢʕĕǠ̓ʪ0͋˗Ȍ˰ʱi̷͐ʷʀʂ̺ʻƬ̾ùĩ˴Ŭƚ̼ƿƯȦǏ˩Ȫȧ̆ȯˑȲ˔ʘˮ˘͚˜ʝ˟ʳˆͳ7929Ǟ˫͚˯ʰȑ̤ͬ͟İŮͦųfȞtɃ˿ȧ19ΞΟΠΡʦ̄Ͷˎ͸ȱ˓ȴ˚ȷ͢˙˖΀˞ʟȽ͇ʣǎΈ8Ȩ3˫95··ǘ˷"QǄė΄ƻ͗Ő͙ͼάeʯ˱ΐȹͯhighpɢċʿȗƻͯ˺ȞȠȢȤͲǅȩΤǏ18˩Ǒƅ̂̇Ά̃˖̛Ƚć̏Ⱦ̒ΚɅė̖ɏ̘ϺɎɐ;ɓɕɗəɛϹ"ɞȏ̧tɤɦɨɪ[ɺ͡ŐfǴɂ̻ʼʉˇψ̜δ͔ЇsɈo̩Џ˳ϋʚ͍΁βĀО͉3ʧʩωΌǧώ͞͠ɽɿЕlЗΕĢʽġϚ˵Ɣ˸Ƭˆϣ.ʹϦϤȅΩϫ0ϭǕ̋ͽέͿЩα͐φг͜Ύ˲͊ˀŬňфųцˈͶˋȧ3ь̊2ϬǒёЧϲήʙΰ͏΃ˢǏǈˬѰд͝ΏˠɌ]}`
        } as Record<string,string>

    for (const name in presets) {
        presets[name] = //presets[name]
            LZW_decompress(presets[name], true)
            // .replace(
            //     /"title":".*?",/g, 
            //     '')
    }

    const div = D('graph-preset-list') as HTMLDivElement
 
    for (const name in presets) {
        const item = E('button', {
            className: 'list-btn',
            text: name
            })
        div.appendChild(item)
    }

    div.onclick = function(e : MouseEvent) {
        const name = (e.target as HTMLElement).innerText
        if (name in presets) {
            GraphController.save()
            GraphController.closeAllWindows()
            GraphController.fromString((<Indexed>presets)[name])
            GraphController.renderer.render()
        }
    }

    Apply_The_Default_Preset: {

        // GraphController.fromString(presets['Keyboard 1'])
        GraphController.renderer.render()
    }
}